name: Build and Push All Services

on:
  push:
    branches:
      - main

jobs:
  build-result:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push result image
        uses: docker/build-push-action@v5
        with:
          context: ./result
          push: true
          tags: sjh980701/examplevotingapp_result:latest

  build-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push worker image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          tags: sjh980701/examplevotingapp_worker:latest

  build-vote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push vote image
        uses: docker/build-push-action@v5
        with:
          context: ./vote
          push: true
          tags: sjh980701/examplevotingapp_vote:latest

